name = "mopkg"
uuid = "ad07cd62-27cc-492b-8f5d-300bdff5607e"
authors = ["Robert-Kwiatkowski"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
